//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickReportLib.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickReportLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BevelLineDown {
            get {
                object obj = ResourceManager.GetObject("BevelLineDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BevelLineUp {
            get {
                object obj = ResourceManager.GetObject("BevelLineUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderAll {
            get {
                object obj = ResourceManager.GetObject("BorderAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderAround {
            get {
                object obj = ResourceManager.GetObject("BorderAround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderBottom {
            get {
                object obj = ResourceManager.GetObject("BorderBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderLeft {
            get {
                object obj = ResourceManager.GetObject("BorderLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderRight {
            get {
                object obj = ResourceManager.GetObject("BorderRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderTop {
            get {
                object obj = ResourceManager.GetObject("BorderTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Color {
            get {
                object obj = ResourceManager.GetObject("Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Column {
            get {
                object obj = ResourceManager.GetObject("Column", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnTotalSum {
            get {
                object obj = ResourceManager.GetObject("ColumnTotalSum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condition {
            get {
                object obj = ResourceManager.GetObject("Condition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrossStyleWizardColumn {
            get {
                object obj = ResourceManager.GetObject("CrossStyleWizardColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrossStyleWizardRow {
            get {
                object obj = ResourceManager.GetObject("CrossStyleWizardRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrossStyleWizardRowText {
            get {
                object obj = ResourceManager.GetObject("CrossStyleWizardRowText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrossStyleWizardValue {
            get {
                object obj = ResourceManager.GetObject("CrossStyleWizardValue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CustomColumnCrossStylePreview {
            get {
                object obj = ResourceManager.GetObject("CustomColumnCrossStylePreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Date {
            get {
                object obj = ResourceManager.GetObject("Date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DateTime {
            get {
                object obj = ResourceManager.GetObject("DateTime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DecimalPlace {
            get {
                object obj = ResourceManager.GetObject("DecimalPlace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteOne {
            get {
                object obj = ResourceManager.GetObject("DeleteOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Department {
            get {
                object obj = ResourceManager.GetObject("Department", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donamic {
            get {
                object obj = ResourceManager.GetObject("Donamic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeneralCrossStylePreview {
            get {
                object obj = ResourceManager.GetObject("GeneralCrossStylePreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GridStylePreview {
            get {
                object obj = ResourceManager.GetObject("GridStylePreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HAlignmentCenter {
            get {
                object obj = ResourceManager.GetObject("HAlignmentCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HAlignmentLeft {
            get {
                object obj = ResourceManager.GetObject("HAlignmentLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HAlignmentRight {
            get {
                object obj = ResourceManager.GetObject("HAlignmentRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutPreview_ConditionTop_TreeBottomLeft_MainBottomRightTop_DetailBottomRightBottom {
            get {
                object obj = ResourceManager.GetObject("LayoutPreview_ConditionTop_TreeBottomLeft_MainBottomRightTop_DetailBottomRightBot" +
                        "tom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_ConditionTop_MainBottom {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_ConditionTop_MainBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_ConditionTop_TreeBottomLeft_MainBottomRight {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_ConditionTop_TreeBottomLeft_MainBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_Main {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_Main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_MainTop_DetailBottom {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_MainTop_DetailBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_TreeLeft_ConditionRightTop_MainRightBottom {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_TreeLeft_ConditionRightTop_MainRightBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_TreeLeft_ConditionRightTop_MainRightBottomTop_DetaiRightBottomBottom {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_TreeLeft_ConditionRightTop_MainRightBottomTop_DetaiRightBottom" +
                        "Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_TreeLeft_MainRight {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_TreeLeft_MainRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutStylePreview_TreeLeft_MainRightTop_DetailRightBottom {
            get {
                object obj = ResourceManager.GetObject("LayoutStylePreview_TreeLeft_MainRightTop_DetailRightBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Merge {
            get {
                object obj = ResourceManager.GetObject("Merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewOne {
            get {
                object obj = ResourceManager.GetObject("NewOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Null {
            get {
                object obj = ResourceManager.GetObject("Null", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Person {
            get {
                object obj = ResourceManager.GetObject("Person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preview {
            get {
                object obj = ResourceManager.GetObject("Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Query {
            get {
                object obj = ResourceManager.GetObject("Query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon QuickReport {
            get {
                object obj = ResourceManager.GetObject("QuickReport", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RowTotalSum {
            get {
                object obj = ResourceManager.GetObject("RowTotalSum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Setting {
            get {
                object obj = ResourceManager.GetObject("Setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Share {
            get {
                object obj = ResourceManager.GetObject("Share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sort {
            get {
                object obj = ResourceManager.GetObject("Sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Span {
            get {
                object obj = ResourceManager.GetObject("Span", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 -- Create table
        ///create table QUICKREPORT_REPORTS
        ///(
        ///  ID      VARCHAR2(38) not null,
        ///  NAME    VARCHAR2(200) not null,
        ///  TYPE    VARCHAR2(100) not null,
        ///  VERSION NUMBER(8,2) not null,
        ///  CONTENT BLOB,
        ///  ISVALID VARCHAR2(1) default 1 not null
        ///)
        ///tablespace USERS
        ///  pctfree 10
        ///  initrans 1
        ///  maxtrans 255
        ///  storage
        ///  (
        ///    initial 16
        ///    minextents 1
        ///    maxextents unlimited
        ///  );
        ///-- Add comments to the columns 
        ///comment on column QUICKREPORT_REPORTS.ID
        ///  is &apos;编码&apos;;
        ///comment on column QUICKREPOR [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_CreateTableQUICKREPORT_REPORTS {
            get {
                return ResourceManager.GetString("SQL_CreateTableQUICKREPORT_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- Create table
        ///create table QUICKREPORT_SETTINGS
        ///(
        ///  OPER_CODE VARCHAR2(12) not null,
        ///  REPORT_ID VARCHAR2(38) not null,
        ///  CONTENT   BLOB,
        ///  SHARED    NVARCHAR2(1) default 0 not null
        ///)
        ///tablespace USERS
        ///  pctfree 10
        ///  initrans 1
        ///  maxtrans 255
        ///  storage
        ///  (
        ///    initial 64K
        ///    minextents 1
        ///    maxextents unlimited
        ///  );
        ///-- Add comments to the columns 
        ///comment on column QUICKREPORT_SETTINGS.OPER_CODE
        ///  is &apos;员工编码&apos;;
        ///comment on column QUICKREPORT_SETTINGS.REPORT_ID
        ///  is &apos;报表ID&apos;;
        ///comment on c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_CreateTableQUICKREPORT_SETTINGS {
            get {
                return ResourceManager.GetString("SQL_CreateTableQUICKREPORT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from quickreport_reports where quickreport_reports.id = &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_DeleteQuickReportByID {
            get {
                return ResourceManager.GetString("SQL_DeleteQuickReportByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO quickreport_reports
        ///  (quickreport_reports.id,
        ///   quickreport_reports.name,
        ///   quickreport_reports.type,
        ///   quickreport_reports.version,
        ///   quickreport_reports.isvalid)
        ///VALUES
        ///  (&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, &apos;{3}&apos;, &apos;{4}&apos;) 的本地化字符串。
        /// </summary>
        internal static string SQL_InsertQuickReportBaseInfo {
            get {
                return ResourceManager.GetString("SQL_InsertQuickReportBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO quickreport_settings
        ///  (quickreport_settings.oper_code, quickreport_settings.report_id)
        ///VALUES
        ///  (&apos;{0}&apos;, &apos;{1}&apos;) 的本地化字符串。
        /// </summary>
        internal static string SQL_InsertSettingBaseInfo {
            get {
                return ResourceManager.GetString("SQL_InsertSettingBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select quickreport_reports.id,
        ///       quickreport_reports.name,
        ///       quickreport_reports.type,
        ///       quickreport_reports.version,
        ///       quickreport_reports.isvalid
        ///  from quickreport_reports
        /// order by quickreport_reports.type , quickreport_reports.id 的本地化字符串。
        /// </summary>
        internal static string SQL_QueryAllReports {
            get {
                return ResourceManager.GetString("SQL_QueryAllReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select distinct quickreport_reports.type
        ///  from quickreport_reports
        /// order by quickreport_reports.type 的本地化字符串。
        /// </summary>
        internal static string SQL_QueryAllReportTypes {
            get {
                return ResourceManager.GetString("SQL_QueryAllReportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select quickreport_reports.id,
        ///       quickreport_reports.name,
        ///       quickreport_reports.type,
        ///       quickreport_reports.version,
        ///       quickreport_reports.content,
        ///       quickreport_reports.isvalid
        ///  from quickreport_reports
        /// where quickreport_reports.id=&apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QueryReportByID {
            get {
                return ResourceManager.GetString("SQL_QueryReportByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select quickreport_settings.content
        ///  from quickreport_settings
        /// where quickreport_settings.oper_code = &apos;{0}&apos;
        ///   and quickreport_settings.report_id = &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QuerySettingByOperCodeAndReportID {
            get {
                return ResourceManager.GetString("SQL_QuerySettingByOperCodeAndReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select *
        ///  from quickreport_settings
        /// where quickreport_settings.oper_code = &apos;{0}&apos;
        ///   and quickreport_settings.report_id = &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QuerySettingExist {
            get {
                return ResourceManager.GetString("SQL_QuerySettingExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select quickreport_settings.content
        ///  from quickreport_settings
        /// where quickreport_settings.report_id = &apos;{0}&apos;
        ///   and quickreport_settings.shared=&apos;1&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QuerySharedSettingByReportID {
            get {
                return ResourceManager.GetString("SQL_QuerySharedSettingByReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select com_employee.empl_name
        ///  from quickreport_settings,com_employee
        /// where 
        ///       quickreport_settings.oper_code=com_employee.empl_code(+)
        ///   and quickreport_settings.oper_code = &apos;{0}&apos;
        ///   and quickreport_settings.report_id = &apos;{1}&apos; 
        ///   and quickreport_settings.shared=&apos;1&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QuerySharedSettingExistByOperCodeAndReportID {
            get {
                return ResourceManager.GetString("SQL_QuerySharedSettingExistByOperCodeAndReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select com_employee.empl_name
        ///  from quickreport_settings,com_employee
        /// where 
        ///       quickreport_settings.oper_code=com_employee.empl_code(+)
        ///   and quickreport_settings.report_id = &apos;{0}&apos; 
        ///   and quickreport_settings.shared=&apos;1&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QuerySharedSettingExistByReportID {
            get {
                return ResourceManager.GetString("SQL_QuerySharedSettingExistByReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select table_name
        ///  from user_all_tables
        /// where table_name = &apos;QUICKREPORT_REPORTS&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QueryTableExistQUICKREPORT_REPORTS {
            get {
                return ResourceManager.GetString("SQL_QueryTableExistQUICKREPORT_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select table_name
        ///  from user_all_tables
        /// where table_name = &apos;QUICKREPORT_SETTINGS&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_QueryTableExistQUICKREPORT_SETTINGS {
            get {
                return ResourceManager.GetString("SQL_QueryTableExistQUICKREPORT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update quickreport_reports
        ///   set quickreport_reports.id      = &apos;{0}&apos;,
        ///       quickreport_reports.name    = &apos;{1}&apos;,
        ///       quickreport_reports.type    = &apos;{2}&apos;,
        ///       quickreport_reports.version =&apos;{3}&apos;,
        ///       quickreport_reports.content = :c,
        ///       quickreport_reports.isvalid = &apos;{4}&apos;
        /// where quickreport_reports.id = &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_UpdateQuickReport {
            get {
                return ResourceManager.GetString("SQL_UpdateQuickReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update quickreport_reports
        ///   set quickreport_reports.content = :c
        /// where quickreport_reports.id = &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_UpdateQuickReportContentByID {
            get {
                return ResourceManager.GetString("SQL_UpdateQuickReportContentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update quickreport_settings
        ///   set quickreport_settings.content = :c
        /// where quickreport_settings.oper_code = &apos;{0}&apos;
        ///   and quickreport_settings.report_id = &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_UpdateSettingByOperCodeAndReportID {
            get {
                return ResourceManager.GetString("SQL_UpdateSettingByOperCodeAndReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update quickreport_settings
        ///   set quickreport_settings.shared = &apos;{2}&apos;
        /// where quickreport_settings.oper_code = &apos;{0}&apos;
        ///   and quickreport_settings.report_id = &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string SQL_UpdateSharedSettingFlagByOperCodeAndReportID {
            get {
                return ResourceManager.GetString("SQL_UpdateSharedSettingFlagByOperCodeAndReportID", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tree {
            get {
                object obj = ResourceManager.GetObject("Tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unlock {
            get {
                object obj = ResourceManager.GetObject("Unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VAlignmentBottom {
            get {
                object obj = ResourceManager.GetObject("VAlignmentBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VAlignmentCenter {
            get {
                object obj = ResourceManager.GetObject("VAlignmentCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VAlignmentTop {
            get {
                object obj = ResourceManager.GetObject("VAlignmentTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ValueTranslateType {
            get {
                object obj = ResourceManager.GetObject("ValueTranslateType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
